### ISSUE TITLE
Do you plan to support urn:ietf:params:scim:schemas:extension:enterprise:2.0:User ?

### ISSUE THREAD

**Issue by hakimMaharmeh** [wso2/charon#100]
**Description:**

Hi,
I do love your SCIM implementations and micro-services. But only urn:ietf:params:scim:schemas:core:2.0:User is implemented in charon-core. Do you plan to support urn:ietf:params:scim:schemas:extension:enterprise:2.0:User ? 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by pcameron1** [comment]
I also found the same thing.
Why is this closed with no comment? 
The readme.md should at least be modified to exclude references saying it is...
