### ISSUE TITLE
filtering uses wrong syntax

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [wso2/charon#116]
according to RFC7644 chapter 3.4.2.2 filter values need to be surrounded by quotemarks

filter=userName eq "bjensen"

but charon rejects such a filter with the following error message:

{"responseStatus":400,"responseMessage":"{\"schemas\":\"urn:ietf:params:scim:api:messages:2.0:Error\",\"scimType\":\"InvalidFilter\",\"detail\":\"Given filter operator is not supported.\",\"status\":\"400\"}","headerParamMap":{"Content-Type":"application/scim+json"}}

removing the quotemarks stops the error

**Comment by IsuraD** [comment]
This is already fixed in https://github.com/wso2/charon/pull/102
