### ISSUE TITLE
Mutually exclusive query parameters?

### ISSUE THREAD

**Issue by donaldquixote** [wso2/charon#44]
Hi WSO2 team!

I've been evaluating Charon-core for use in a project, and while most everything is looking great so far, I have one concern. I noticed that the interfaces for UserManager, as well as the user and group endpoints, seem to force mutual exclusion across the different query parameters. The sample implementation in Charon-impl reinforces this (e.g. I can call GET /users with both the attributes and sortby query parms, but only the attributes parm would be honored).

Am I misunderstanding the code or the SCIM spec, or is there something else I am missing? My understanding of SCIM queries is that I should be able to perform a search using any subset of the four capabilities (filter, attribute, sort, paginate).

Thanks, and keep up the good work with Charon and Identity Server!

**Comment by cdwijayarathna** [comment]
Hi @donaldquixote ,

Thank for evaluating charon.

Currently charon only provides a limited set functionalities of SCIM spec and there are some more to be implemented as mentioned in https://wso2.org/jira/browse/IDENTITY-3134 . So from the capabilities you have listed, we only support filter param and from its operations only 'eq'. So we have long way to go and we'll try to provide them soon.

If you are blocking on any of these features, please improve the priority of relavant jira. Also you are mostly welcome to contribute.

Cheers!
