### ISSUE TITLE
charon 2.0.5 JSONDecoder doesn't decode boolean sub-attributes

### ISSUE THREAD

**Issue by adnanalawiyat** [wso2/charon#71]
This is specific to charon v.2.0.5
When a user json object contains a sub-attribute with a boolean value such as emails.primary, org.wso2.charon.core.encoder.json.JSONDecoder fails to decode the string properly to a User object.

code snippet:

```java
    String userJson = "{\n" +
            "  \"schemas\": [\"urn:ietf:params:scim:schemas:core:2.0:User\"],\n" +
            "  \"userName\": \"testUser\",\n" +
            "  \"emails\": [{\n" +
            "      \"value\": \"test@example.com\",\n" +
            "      \"primary\": true\n" +
            "  }]\n" +
            "}";
    SCIMResourceSchema userSchema = SCIMResourceSchemaManager
            .getInstance().getUserResourceSchema();
    User user = new User();
    user = (User) new JSONDecoder()
            .decodeResource(userJson, userSchema, user);
```

user object from above snippet doesn't contain "primary" sub attribute.

**Comment by pieterjanpintens** [comment]
Seeing the same thing when trying to sync azure active directory to charon3.
I noticed that for some reason in org.wso2.charon3.core.utils.AttributeUtil the boolean value is handled differently. I modified this and now it seems to be working.

Is there a reason why it is handled differently and not just like the other primary types?

**Comment by omindu** [comment]
Fixed with https://github.com/wso2/charon/commit/6facd65335acb69e2125505e0ad93cc069b7bfca
