### ISSUE TITLE
Filter User by phoneNumber.value issue

### ISSUE THREAD

**Issue by hungphamvn** [wso2/charon#95]
**Description:**

I'm trying to check whether phone number existing in WSO2 IS or not. And the problem is when I provided a number as filter's value and response i got is "'{"schemas":"urn:ietf:params:scim:api:messages:2.0:Error","scimType":"InvalidFilter","detail":"Given filter operator is not supported.","status":"400"}'"

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
POST :" response = requests.get(https://localhost:9443/scim2/Users?filter=phoneNumbers.value+Eq+\"%s\"' % (0912345, ), auth=('admin', 'admin'), verify=False)
and response it's what i'm mention above..
So, Please respond and help me so this issue, thank a lot!!
**Related Issues:**

**Comment by Captain-P-Goldfish** [comment]
nice, nobody answered this. If the problem still remains see this issue that will hopefully clarify the problem

#116

**Comment by IsuraD** [comment]
This is already fixed in https://github.com/wso2/charon/pull/102
